# train.py Config - Training
train:
  # Synthetic datasets with ground truth labelsinp, output shapes :
  datasetsTrain:
      - normals: 'data/datasets/train/sphere-bath-bomb-train/source-files/camera-normals'
        images: 'data/datasets/train/sphere-bath-bomb-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/sphere-bath-bomb-train/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/train/tree-bath-bomb-train/source-files/camera-normals'
        images: 'data/datasets/train/tree-bath-bomb-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/tree-bath-bomb-train/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/train/cup-with-waves-train/source-files/camera-normals'
        images: 'data/datasets/train/cup-with-waves-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/cup-with-waves-train/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/train/heart-bath-bomb-train/source-files/camera-normals'
        images: 'data/datasets/train/heart-bath-bomb-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/heart-bath-bomb-train/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/train/stemless-champagne-glass-train/source-files/camera-normals'
        images: 'data/datasets/train/stemless-champagne-glass-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/stemless-champagne-glass-train/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/train/flower-bath-bomb-train/source-files/camera-normals'
        images: 'data/datasets/train/flower-bath-bomb-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/flower-bath-bomb-train/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/train/short-bottle-with-cap-train/source-files/camera-normals'
        images: 'data/datasets/train/short-bottle-with-cap-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/short-bottle-with-cap-train/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/train/milk-bottles-in-boxes-train/source-files/camera-normals'
        images: 'data/datasets/train/milk-bottles-in-boxes-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/milk-bottles-in-boxes-train/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/train/milk-bottles-train/source-files/camera-normals'
        images: 'data/datasets/train/milk-bottles-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/milk-bottles-train/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/train/scoop-train/source-files/camera-normals'
        images: 'data/datasets/train/scoop-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/scoop-train/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/train/test-tube-with-cap-train/source-files/camera-normals'
        images: 'data/datasets/train/test-tube-with-cap-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/test-tube-with-cap-train/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/train/test-tube-no-cap-train/source-files/camera-normals'
        images: 'data/datasets/train/test-tube-no-cap-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/test-tube-no-cap-train/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/train/short-bottle-no-cap-train/source-files/camera-normals'
        images: 'data/datasets/train/short-bottle-no-cap-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/short-bottle-no-cap-train/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/train/hearts-in-containers-train/source-files/camera-normals'
        images: 'data/datasets/train/hearts-in-containers-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/hearts-in-containers-train/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/train/stemless-plastic-champagne-glasses-lying-flat-train/source-files/camera-normals'
        images: 'data/datasets/train/stemless-plastic-champagne-glasses-lying-flat-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/stemless-plastic-champagne-glasses-lying-flat-train/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/train/square-clear-plastic-bottle-lying-flat-train/source-files/camera-normals'
        images: 'data/datasets/train/square-clear-plastic-bottle-lying-flat-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/square-clear-plastic-bottle-lying-flat-train/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/train/star-bath-bomb-train/source-files/camera-normals'
        images: 'data/datasets/train/star-bath-bomb-train/source-files/rgb-imgs'
        labels: 'data/datasets/train/star-bath-bomb-train/source-files/depth-imgs-rectified'


  # Synthetic datasets with ground truth labels - 10% split of train
  datasetsVal:
      - normals: 'data/datasets/val/sphere-bath-bomb-val/source-files/camera-normals'
        images: 'data/datasets/val/sphere-bath-bomb-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/sphere-bath-bomb-val/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/val/tree-bath-bomb-val/source-files/camera-normals'
        images: 'data/datasets/val/tree-bath-bomb-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/tree-bath-bomb-val/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/val/cup-with-waves-val/source-files/camera-normals'
        images: 'data/datasets/val/cup-with-waves-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/cup-with-waves-val/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/val/heart-bath-bomb-val/source-files/camera-normals'
        images: 'data/datasets/val/heart-bath-bomb-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/heart-bath-bomb-val/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/val/stemless-champagne-glass-val/source-files/camera-normals'
        images: 'data/datasets/val/stemless-champagne-glass-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/stemless-champagne-glass-val/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/val/flower-bath-bomb-val/source-files/camera-normals'
        images: 'data/datasets/val/flower-bath-bomb-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/flower-bath-bomb-val/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/val/short-bottle-with-cap-val/source-files/camera-normals'
        images: 'data/datasets/val/short-bottle-with-cap-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/short-bottle-with-cap-val/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/val/milk-bottles-in-boxes-val/source-files/camera-normals'
        images: 'data/datasets/val/milk-bottles-in-boxes-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/milk-bottles-in-boxes-val/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/val/milk-bottles-val/source-files/camera-normals'
        images: 'data/datasets/val/milk-bottles-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/milk-bottles-val/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/val/scoop-val/source-files/camera-normals'
        images: 'data/datasets/val/scoop-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/scoop-val/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/val/test-tube-with-cap-val/source-files/camera-normals'
        images: 'data/datasets/val/test-tube-with-cap-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/test-tube-with-cap-val/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/val/test-tube-no-cap-val/source-files/camera-normals'
        images: 'data/datasets/val/test-tube-no-cap-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/test-tube-no-cap-val/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/val/short-bottle-no-cap-val/source-files/camera-normals'
        images: 'data/datasets/val/short-bottle-no-cap-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/short-bottle-no-cap-val/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/val/hearts-in-containers-val/source-files/camera-normals'
        images: 'data/datasets/val/hearts-in-containers-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/hearts-in-containers-val/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/val/stemless-plastic-champagne-glasses-lying-flat-val/source-files/camera-normals'
        images: 'data/datasets/val/stemless-plastic-champagne-glasses-lying-flat-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/stemless-plastic-champagne-glasses-lying-flat-val/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/val/square-clear-plastic-bottle-lying-flat-val/source-files/camera-normals'
        images: 'data/datasets/val/square-clear-plastic-bottle-lying-flat-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/square-clear-plastic-bottle-lying-flat-val/source-files/depth-imgs-rectified'
      - normals: 'data/datasets/val/star-bath-bomb-val/source-files/camera-normals'
        images: 'data/datasets/val/star-bath-bomb-val/source-files/rgb-imgs'
        labels: 'data/datasets/val/star-bath-bomb-val/source-files/depth-imgs-rectified'

 # Training/Validation Params
  model: 'rednet' # Possible values - [ 'rednet', 'deeplab_xception', 'deeplab_resnet']
  batchSize: 4
  numEpochs: 500
  imgHeight: 256
  imgWidth: 256
  numClasses: 1
  numInputChannels: 3 # Num of channels in input image. Normals+Depth = 4 channels, Only_Normals = 3 channles, Grayscale = 1 channel.
  numWorkers: 12 # Num of workers used in the dataloader
  logsDir: 'logs' # Directory where logs of each exp will be saved.
  useMaskforLoss: False # Whether to calc loss over entire image, or only over masked area.
  concat_depth: False # Whether to concat depth with normals as input or use only normals.
  loss_type: 'l1' # Possible values - ['l1', 'l2']. Type of loss to use for back propagation
  normalize_depth: True # whether the labels and outputs must be de-normalized or not
  percentageDataForTraining: 1.0 # The percentage of images in dataset to be used for training. Rest used for validation.
  validationBatchSize: 50
  percentageDataForValidation: 1.0
  testBatchSize: 50
  outputStride: 16 # Possible values - [8, 16]. Output stride for deeplabv3 model. Smaller values give finer details in output mask.


  min_depth: 0.0
  max_depth: 3.0

  continueTraining: True  # If true, continue training from a checkpoint
  pathPrevCheckpoint: 'logs/exp-003/checkpoints/checkpoint-epoch-0080.pth' # Path to .pth checkpoint file to load to continue training from
  initOptimizerFromCheckpoint: False  # Re-Initialize optimizer's state from checkpoint. NOTE: when this is enabled, value of learningRate will be overridden with value from checkpoint.
  loadEpochNumberFromCheckpoint: True # If true, the epoch/iter numbering will start from the checkpoint's last epoch num.

  saveImageInterval: 5 # Log output images to tensorboard every saveImageInterval epochs
  testInterval: 1 # Run on test set every nTestInterval epochs. Keep at 0 to skip tests.
  saveModelInterval: 10 # Save the model checkpoints every N epochs


  # Optimizer Params
  optimAdam:
    learningRate: 0.001
    beta1: 0.9
    beta2: 0.999
    weightDecay: 0 # Other values: 0.0001
  optimSgd:
    learningRate: 1e-3  # 2e-3 
    momentum: 0.9
    weight_decay: 4e-4 #5e-4
  lrScheduler: 'StepLR' # Possible Values - ['', 'StepLR', 'ReduceLROnPlateau', 'lr_poly', 'LambdaLR'] # lr_poly used for deeplabv3+
  lrSchedulerStep:
    step_size: 5
    gamma: 0.8
  lrSchedulerPlateau:
    factor: 0.8
    patience: 25
    verbose: True
  lrPoly:
    epochSize: 1 # After these many epochs, change learning rate
    decay: 0.7
  LambdaLR: # rednet
    lr_decay_rate: 0.8
    lr_epoch_per_decay: 10

# eval.py Config - Validation/Testing Inference
eval:
  # Synthetic datasets with ground truth labels
  # Used as validation set
  datasetsSynthetic:
    # - normals: 'data/datasets/val/milk-bottles-val/source-files/camera-normals'
    #   variant_masks: 'data/datasets/val/milk-bottles-val/source-files/variant-masks'
    #   json: 'data/datasets/val/milk-bottles-val/source-files/json-files'
    #   labels: 'data/datasets/val/milk-bottles-val/source-files/depth-imgs-rectified'
    - normals: 'data/datasets/val/stemless-plastic-champagne-glasses-lying-flat-val/source-files/camera-normals'
      variant_masks: 'data/datasets/val/stemless-plastic-champagne-glasses-lying-flat-val/source-files/variant-masks'
      json: 'data/datasets/val/stemless-plastic-champagne-glasses-lying-flat-val/source-files/json-files'
      labels: 'data/datasets/val/stemless-plastic-champagne-glasses-lying-flat-val/source-files/depth-imgs-rectified'

  # Datasets of real images, no labels available
  # Used as Test set
  datasetsReal:
    - images: '' #'data/datasets/test/camera-pics/resized-files/preprocessed-rgb-imgs'
    - images: ' ' # /home/gani/deeplearning/brain/datasets/test/realsense-demo-table/source-files/rgb-imgs'

  # Params
  mode: 'depth'
  model: 'rednet' # Possible values: ['rednet', 'unet', 'deeplab_xception', 'deeplab_resnet']
  numClasses: 1
  numInputChannels: 3
  batchSize: 16
  outputStride: 16
  imgHeight: 256
  imgWidth: 256
  numWorkers: 8 # Num of workers used in the dataloader
  pathWeightsFile: 'logs/exp-050/checkpoints/checkpoint-epoch-0340.pth' # Path to the checkpoint to be loaded
  resultsDirSynthetic: 'data/results/test-synthetic' # The dir to which results on synthetic images will be stored
  resultsDirReal: 'data/results/test-real'  # The dir to which results on real images will be stored
  resultsWeightsSubDir: 'occlusion-weights' # The prediction of model will be converted to occlusion weights (for depth2depth) in this subfolder within each results folder
  resultsWeightsVizSubDir: 'occlusion-weights-viz' # The visualization of the occlusion weights will be saved in this subfolder within resultsWeightsSubDir